# Dongle-specific configuration

# Increase BT TX power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Split keyboard configuration - dongle expects 2 peripherals (left + right)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
