manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: studio-rpc-usb-uart
      remote: zmkfirmware
      revision: main
      path: app/modules/studio-rpc-usb-uart
  self:
    path: config
